/* ISC license. */

#ifndef PAMELA_COMMON_H
#define PAMELA_COMMON_H

#define PAMELA_BUFSIZE 4096

enum pamela_retcode_e
{
  PAMELA_PAM_SUCCESS = 0,
  PAMELA_PAM_OPEN_ERR,
  PAMELA_PAM_SYMBOL_ERR,
  PAMELA_PAM_SERVICE_ERR,
  PAMELA_PAM_SYSTEM_ERR,
  PAMELA_PAM_BUF_ERR,
  PAMELA_PAM_PERM_DENIED,
  PAMELA_PAM_AUTH_ERR,
  PAMELA_PAM_CRED_INSUFFICIENT,
  PAMELA_PAM_AUTHINFO_UNAVAIL,
  PAMELA_PAM_USER_UNKNOWN,
  PAMELA_PAM_MAXTRIES,
  PAMELA_PAM_NEW_AUTHTOK_REQD,
  PAMELA_PAM_ACCT_EXPIRED,
  PAMELA_PAM_SESSION_ERR,
  PAMELA_PAM_CRED_UNAVAIL,
  PAMELA_PAM_CRED_EXPIRED,
  PAMELA_PAM_CRED_ERR,
  PAMELA_PAM_NO_MODULE_DATA,
  PAMELA_PAM_CONV_ERR,
  PAMELA_PAM_AUTHTOK_ERR,
  PAMELA_PAM_AUTHTOK_RECOVERY_ERR,
  PAMELA_PAM_AUTHTOK_LOCK_BUSY,
  PAMELA_PAM_AUTHTOK_DISABLE_AGING,
  PAMELA_PAM_TRY_AGAIN,
  PAMELA_PAM_IGNORE,
  PAMELA_PAM_ABORT,
  PAMELA_PAM_AUTHTOK_EXPIRED,
  PAMELA_PAM_MODULE_UNKNOWN,
  PAMELA_PAM_BAD_ITEM,
  PAMELA_PAM_CONV_AGAIN,
  PAMELA_PAM_INCOMPLETE
} ;


enum pamela_item_e
{
  PAMELA_ENV = 0,
  PAMELA_PAM_SERVICE,
  PAMELA_PAM_USER,
  PAMELA_PAM_TTY,
  PAMELA_PAM_RHOST,
  PAMELA_PAM_CONV,
  PAMELA_PAM_AUTHTOK,
  PAMELA_PAM_OLDAUTHTOK,
  PAMELA_PAM_RUSER,
  PAMELA_PAM_USER_PROMPT,
  PAMELA_PAM_FAIL_DELAY,
  PAMELA_PAM_XDISPLAY,
  PAMELA_PAM_XAUTHDATA,
  PAMELA_PAM_AUTHTOK_TYPE
} ;


enum pamela_convmsgtype_e
{
  PAMELA_PAM_PROMPT_ECHO_OFF = 1,
  PAMELA_PAM_PROMPT_ECHO_ON,
  PAMELA_PAM_ERROR_MSG,
  PAMELA_PAM_TEXT_INFO,
  PAMELA_PAM_RADIO_TYPE,
  PAMELA_PAM_BINARY_PROMPT = 7
} ;

#define PAMELA_PAM_CONV_MAX_MESSAGES 1024


enum pamela_op_e
{
  PAMELA_OP_ACCT_MGMT = 1,
  PAMELA_OP_AUTHENTICATE,
  PAMELA_OP_CHAUTHTOK,
  PAMELA_OP_CLOSE_SESSION,
  PAMELA_OP_FAIL_DELAY,
  PAMELA_OP_OPEN_SESSION,
  PAMELA_OP_SETCRED,
  PAMELA_OP_SETFAILDELAY,
  PAMELA_OP_END
} ;


 /* flags */

#define PAMELA_PAM_SILENT 0x8000U
#define PAMELA_PAM_DISALLOW_NULL_AUTHTOK 0x0001U
#define PAMELA_PAM_ESTABLISH_CRED 0x0002U
#define PAMELA_PAM_DELETE_CRED 0x0004U
#define PAMELA_PAM_REINITIALIZE_CRED 0x0008U
#define PAMELA_PAM_REFRESH_CRED 0x0010U
#define PAMELA_PAM_CHANGE_EXPIRED_AUTHTOK 0x0020U

#endif
